{
 "title": "Logs",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service",
    "query": {}
   },
   {
    "name": "level",
    "query": {}
   },
   { "name": "search", "label": "Search Text" }
  ]
 },
 "panels": [
  { "title": "Logs by Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({service_name=\"$service_name\", level=~\"$level\"} [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Logs Detailed Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{service_name=\"$service_name\", severity_text=~\"$level\"} |=\"$search\" | line_format `[{{ .severity_text }}] {{ .message_template_text }}`"
    }
   ]
  },
  { "title": "Logs with TraceId Link", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Log Entries with Trace Link",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{service_name=\"$service_name\", level=~\"$level\"} |=\"$search\" | json "
    }
   ]
  }
 ]
}