apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS0wMS5hZGFtdHJpcC5wdCI6eyJhdXRoIjoiY205aWIzUTZaRWM0YW1STU9UbFFhRmxuVTJ0bU4wZHRaRWQxTWtGRGFXaDRWR0psYURFPSIsImVtYWlsIjoiYXNwaXI4QGFrYS5tcyJ9fX0=
